import img from "../images/room.png";

export const properties = [
    {
        id: "123123",
        img: img,
        startingPrice: 1000,
        category: "Buy to let",
        title: "1-Bedroom Apartment near City Center",
        exp_return: 12,
        dvd_yield: 7,
        bnb: 5,
        dvd_freq: "Monthly",
        NFT_mins: 100,
        price: 1000,
        beds: 1,
        listPrice: "$600,000 USD",
        sqf: 950,
        owners: 400,
        nfts: 920,
        annualYield: "10.4%",
        appreciation: "15%",
        roi: "99.5%",
        location: {
            latitude: 25.1972,
            longitude: 55.2744,
            location: "Dubai, UAE"
        },
        currentPrice: "$650",
        status: "Buy Now",
        link: "/marketplace"
    },
    {
        id: "123124",
        img: img,
        startingPrice: 1000,
        category: "Sold",
        title: "Luxury Studio Downtown",
        exp_return: 14,
        dvd_yield: 9,
        bnb: 5,
        dvd_freq: "Quarterly",
        NFT_mins: 150,
        price: 1200,
        beds: 2,
        listPrice: "$750,000 USD",
        sqf: 1150,
        owners: 550,
        nfts: 1000,
        annualYield: "11.8%",
        appreciation: "19%",
        roi: "103.7%",
        location: {
            latitude: 31.579942,
            longitude: 74.354644,
            location: "UET, Lahore pakistan"
        },
        currentPrice: "$780",
        status: "Fully funded",
        link: "/marketplace"
    },
    {
        id: "123125",
        img: img,
        startingPrice: 1000,
        category: "Sold",
        title: "City Center Condo with Stunning Views",
        exp_return: 13,
        dvd_yield: 6,
        bnb: 5,
        dvd_freq: "Monthly",
        NFT_mins: 100,
        price: 1100,
        beds: 1,
        listPrice: "$500,000 USD",
        sqf: 850,
        owners: 420,
        nfts: 830,
        annualYield: "9.5%",
        appreciation: "14%",
        roi: "94.1%",
        location: {
            latitude: 53.800755,
            longitude: -1.549077,
            location: "Leeds, United Kingdom"
        },
        currentPrice: "$520",
        status: "Sold",
        link: "/marketplace"
    },
    {
        id: "123126",
        img: img,
        startingPrice: 1000,
        category: "Sold",
        title: "Modern 3-Bedroom Penthouse",
        exp_return: 15,
        dvd_yield: 10,
        bnb: 5,
        dvd_freq: "Monthly",
        NFT_mins: 200,
        price: 1300,
        beds: 3,
        listPrice: "$850,000 USD",
        sqf: 1500,
        owners: 680,
        nfts: 1350,
        annualYield: "13.2%",
        appreciation: "21%",
        roi: "109.6%",
        location: {
            latitude: 52.486244,
            longitude: -1.890401,
            location: "Birmingham, United Kingdom"
        },
        currentPrice: "$880",
        status: "Fully funded",
        link: "/marketplace"
    },
    {
        id: "123127",
        img: img,
        startingPrice: 1000,
        category: "Buy to let",
        title: "Classic 1-Bedroom Apartment",
        exp_return: 11,
        dvd_yield: 8,
        bnb: 5,
        dvd_freq: "Monthly",
        NFT_mins: 90,
        price: 1050,
        beds: 1,
        listPrice: "$550,000 USD",
        sqf: 940,
        owners: 470,
        nfts: 890,
        annualYield: "10.2%",
        appreciation: "17%",
        roi: "97.8%",
        location: {
            latitude: 55.953251,
            longitude: -3.188267,
            location: "Edinburgh, United Kingdom"
        },
        currentPrice: "$580",
        status: "Buy Now",
        link: "/marketplace"
    },
    {
        id: "123128",
        img: img,
        startingPrice: 1000,
        category: "Sold",
        title: "Spacious 2-Bedroom in Prime Location",
        exp_return: 16,
        dvd_yield: 12,
        bnb: 5,
        dvd_freq: "Quarterly",
        NFT_mins: 160,
        price: 1250,
        beds: 2,
        listPrice: "$900,000 USD",
        sqf: 1300,
        owners: 720,
        nfts: 1520,
        annualYield: "14.8%",
        appreciation: "22%",
        roi: "114.3%",
        location: {
            latitude: 55.864237,
            longitude: -4.251806,
            location: "Glasgow, United Kingdom"
        },
        currentPrice: "$940",
        status: "Sold",
        link: "/marketplace"
    }
];
