import { getRandomFutureTime } from "./getTime";
import img from "../images/room.png";

export const properties = [
    {
        id: "32313",
        img: img,
        category: "Rental Property",
        auctionEndTime: getRandomFutureTime(),
        title: "Luxury 2-Bedroom Apartment in Downtown",
        exp_return: 14,
        dvd_yield: 7,
        dvd_freq: "Monthly",
         bnb: 5,
        bid_percent: "5% below the market price",
        price: 1000,
        beds: 2,
        listPrice: "900,000 USD",
        sqf: 2000,
        owners: 450,
        nfts: 850,
        annualYield: "12.5%",
        appreciation: "18%",
        roi: "105.67%",
        location: {
            latitude: 40.712776,
            longitude: -74.005974,
            location: "New York, USA"
        },
        currentPrice: "900$",
        status: "Available",
        link: "/secondary"
    },
    {
        id: "32314",
        img: img,
        category: "Rental Property",
        auctionEndTime: getRandomFutureTime(),
        title: "Cozy 1-Bedroom Loft in the Suburbs",
        exp_return: 10,
        dvd_yield: 6,
        dvd_freq: "Monthly",
         bnb: 5,
        bid_percent: "15% below the market price",
        price: 1000,
        beds: 1,
        listPrice: "500,000 USD",
        sqf: 1200,
        owners: 350,
        nfts: 500,
        annualYield: "10.2%",
        appreciation: "16%",
        roi: "97.34%",
        location: {
            latitude: 34.052235,
            longitude: -118.243683,
            location: "Los Angeles, USA"
        },
        currentPrice: "500$",
        status: "Buy Now",
        link: "/secondary"
    },
    {
        id: "32315",
        img: img,
        category: "Rental Property",
        auctionEndTime: getRandomFutureTime(),
        title: "Modern 3-Bedroom Apartment with Ocean View",
        exp_return: 16,
        dvd_yield: 9,
        dvd_freq: "Monthly",
         bnb: 5,
        bid_percent: "12% below the market price",
        price: 1000,
        beds: 3,
        listPrice: "1,200,000 USD",
        sqf: 2200,
        owners: 700,
        nfts: 1200,
        annualYield: "15.3%",
        appreciation: "22%",
        roi: "112.45%",
        location: {
            latitude: 25.761681,
            longitude: -80.191788,
            location: "Miami, USA"
        },
        currentPrice: "1200$",
        status: "Available",
        link: "/secondary"
    },
    {
        id: "32316",
        img: img,
        category: "Rental Property",
        auctionEndTime: getRandomFutureTime(),
        title: "Spacious 4-Bedroom Villa in Beverly Hills",
        exp_return: 18,
        dvd_yield: 10,
        dvd_freq: "Monthly",
         bnb: 5,
        bid_percent: "7% below the market price",
        price: 1000,
        beds: 4,
        listPrice: "2,500,000 USD",
        sqf: 3500,
        owners: 1000,
        nfts: 2000,
        annualYield: "18.8%",
        appreciation: "25%",
        roi: "125.75%",
        location: {
            latitude: 34.073620,
            longitude: -118.400356,
            location: "Beverly Hills, USA"
        },
        currentPrice: "2500$",
        status: "Buy Now",
        link: "/secondary"
    },
    {
        id: "32317",
        img: img,
        category: "Rental Property",
        auctionEndTime: getRandomFutureTime(),
        title: "Charming Studio in the Heart of Paris",
        exp_return: 12,
        dvd_yield: 7,
        dvd_freq: "Monthly",
         bnb: 5,
        bid_percent: "10% below the market price",
        price: 1000,
        beds: 1,
        listPrice: "600,000 EUR",
        sqf: 950,
        owners: 500,
        nfts: 900,
        annualYield: "11.4%",
        appreciation: "19%",
        roi: "102.89%",
        location: {
            latitude: 48.856613,
            longitude: 2.352222,
            location: "Paris, France"
        },
        currentPrice: "600$",
        status: "Available",
        link: "/secondary"
    },
    {
        id: "32318",
        img: img,
        category: "Rental Property",
        auctionEndTime: getRandomFutureTime(),
        title: "Elegant 2-Bedroom Penthouse in London",
        exp_return: 15,
        dvd_yield: 8,
        dvd_freq: "Monthly",
         bnb: 5,
        bid_percent: "8% below the market price",
        price: 1000,
        beds: 2,
        listPrice: "1,800,000 GBP",
        sqf: 2400,
        owners: 800,
        nfts: 1100,
        annualYield: "13.6%",
        appreciation: "21%",
        roi: "115.98%",
        location: {
            latitude: 51.507351,
            longitude: -0.127758,
            location: "London, United Kingdom"
        },
        currentPrice: "1800£",
        status: "Buy Now",
        link: "/secondary"
    }
];
