import img from "../images/room.png"

export const properties = [
    {
        id: "34535345",
        img: img,
        startingPrice: 1000,
        category: "Buy to let",
        title: "1-Bedroom studio apartment near the city center",
       
        exp_return: 12,
        dvd_yield: 8,
        dvd_freq: "Monthly",
        NFT_mins: 100,
         bnb: 5,
        price: 1000,
        status: "Buy Now",
        link: "/upcoming",
        beds: 1,
        listPrice: "600,000 EUR",
        sqf: 950,
        owners: 500,
        nfts: 900,
        annualYield: "11.4%",
        appreciation: "19%",
        roi: "102.89%",
        location: {
            latitude: 48.856613,
            longitude: 2.352222,
            location: "Paris, France"
        },
        currentPrice: "600$",
        status: "Buy Now"
    },
    {
        id: "45645678",
        img: img,
        startingPrice: 1200,
        category: "Buy to let",
        title: "2-Bedroom luxury apartment with a river view",
       
        exp_return: 14,
        dvd_yield: 9,
        dvd_freq: "Monthly",
        NFT_mins: 120,
         bnb: 5,
        price: 1000,
        status: "Buy Now",
        link: "/upcoming",
        beds: 2,
        listPrice: "750,000 EUR",
        sqf: 1200,
        owners: 600,
        nfts: 1100,
        annualYield: "12.1%",
        appreciation: "20%",
        roi: "105.32%",
        location: {
            latitude: 53.408371,
            longitude: -2.991573,
            location: "Liverpool, United Kingdom"
        },
        currentPrice: "750$",
        status: "Buy Now"
    },
    {
        id: "56756789",
        img: img,
        startingPrice: 1100,
        category: "Buy to let",
        title: "Modern studio apartment near university campus",
       
        exp_return: 11,
        dvd_yield: 7,
        dvd_freq: "Monthly",
        NFT_mins: 90,
         bnb: 5,
        price: 1000,
        status: "Buy Now",
        link: "/upcoming",
        beds: 1,
        listPrice: "500,000 EUR",
        sqf: 800,
        owners: 450,
        nfts: 850,
        annualYield: "10.5%",
        appreciation: "17%",
        roi: "98.45%",
        location: {
            latitude: 53.800755,
            longitude: -1.549077,
            location: "Leeds, United Kingdom"
        },
        currentPrice: "500$",
        status: "Buy Now"
    },
    {
        id: "67867890",
        img: img,
        startingPrice: 1300,
        category: "Buy to let",
        title: "Spacious 3-Bedroom house with garden access",
       
        exp_return: 13,
        dvd_yield: 10,
        dvd_freq: "Monthly",
        NFT_mins: 150,
         bnb: 5,
        price: 1000,
        status: "Buy Now",
        link: "/upcoming",
        beds: 3,
        listPrice: "850,000 EUR",
        sqf: 1600,
        owners: 700,
        nfts: 1400,
        annualYield: "13.7%",
        appreciation: "22%",
        roi: "112.89%",
        location: {
            latitude: 52.486244,
            longitude: -1.890401,
            location: "Birmingham, United Kingdom"
        },
        currentPrice: "850$",
        status: "Buy Now"
    },
    {
        id: "78978901",
        img: img,
        startingPrice: 1050,
        category: "Buy to let",
        title: "Cozy 1-Bedroom apartment in the heart of downtown",
       
        exp_return: 10,
        dvd_yield: 6,
        dvd_freq: "Monthly",
        NFT_mins: 80,
         bnb: 5,
        price: 1000,
        status: "Buy Now",
        link: "/upcoming",
        beds: 1,
        listPrice: "550,000 EUR",
        sqf: 950,
        owners: 480,
        nfts: 880,
        annualYield: "9.9%",
        appreciation: "18%",
        roi: "101.56%",
        location: {
            latitude: 55.953251,
            longitude: -3.188267,
            location: "Edinburgh, United Kingdom"
        },
        currentPrice: "550$",
        status: "Buy Now"
    },
    {
        id: "89089012",
        img: img,
        startingPrice: 1250,
        category: "Buy to let",
        title: "Luxury penthouse with city skyline view",
       
        exp_return: 15,
        dvd_yield: 11,
        dvd_freq: "Monthly",
        NFT_mins: 160,
         bnb: 5,
        price: 1000,
        status: "Buy Now",
        link: "/upcoming",
        beds: 2,
        listPrice: "900,000 EUR",
        sqf: 1350,
        owners: 750,
        nfts: 1550,
        annualYield: "14.3%",
        appreciation: "23%",
        roi: "115.23%",
        location: {
            latitude: 55.864237,
            longitude: -4.251806,
            location: "Glasgow, United Kingdom"
        },
        currentPrice: "900$",
        status: "Buy Now"
    }
]
