export type ViewMode = 'full' | 'tenant' | 'admin' | 'payment' | 'booking' | 'crypto';

export interface FlowView {
  id: ViewMode;
  label: string;
  icon: string;
  nodeIds: string[];
  defaultStartId: string;
  description: string;
}

export const FLOW_VIEWS: FlowView[] = [
  {
    id: 'full',
    label: 'Full Map',
    icon: '🗺',
    nodeIds: [], // empty = all nodes
    defaultStartId: 'visitor',
    description: 'All 103 nodes across every business domain',
  },
  {
    id: 'tenant',
    label: 'Tenant Journey',
    icon: '👤',
    defaultStartId: 'visitor',
    description: 'How a visitor signs up, pays, and sends inquiries',
    nodeIds: [
      'visitor',
      'signup',
      'social-login',
      'particle-callback',
      'otp-verify',
      'free-dashboard',
      'upgrade-prompt',
      'payment-modal',
      'ghl-cart',
      'upsell',
      'downsell',
      'thank-you-ghl',
      'ghl-payment-webhook',
      'tier-update',
      'payment-success-detect',
      'paid-dashboard',
      'browse-deals',
      'deal-detail',
      'inquiry-panel',
      'process-inquiry',
      'inquiry-row',
      'landlord-invite-insert',
      'ghl-enroll-tenant',
      'whatsapp-open',
    ],
  },
  {
    id: 'admin',
    label: 'Admin Flow',
    icon: '🛡',
    defaultStartId: 'admin-dashboard',
    description: 'How admin reviews deals, manages outreach, and releases landlord contacts',
    nodeIds: [
      'admin-dashboard',
      'admin-quick-list',
      'ai-parse-listing',
      'admin-deals',
      'deal-approved',
      'admin-outreach',
      'admin-release-gate',
      'ghl-enroll-admin',
      'landlord-ghl-message',
      'admin-users',
      'hard-delete-user',
      'admin-notifications',
      'deal-expiry',
      'send-email',
      'notifications-bell',
      'inquiry-notification',
    ],
  },
  {
    id: 'payment',
    label: 'Payments',
    icon: '💳',
    defaultStartId: 'upgrade-prompt',
    description: 'Payment funnel, GHL cart, tier webhooks, and bank payout pipeline',
    nodeIds: [
      'upgrade-prompt',
      'payment-modal',
      'ghl-cart',
      'upsell',
      'downsell',
      'thank-you-ghl',
      'ghl-payment-webhook',
      'tier-update',
      'payment-success-detect',
      'save-bank-details',
      'submit-payout-claim',
      'revolut-pay',
      'revolut-token-refresh',
      'revolut-webhook',
      'bank-payout-complete',
      'n8n-tuesday-batch',
      'admin-invest-payouts',
    ],
  },
  {
    id: 'booking',
    label: 'Booking',
    icon: '🏠',
    defaultStartId: 'nfs-operator-onboarding',
    description: 'nfstay.app: operator onboarding, property listing, guest checkout',
    nodeIds: [
      'nfs-operator-onboarding',
      'nfs-stripe-connect',
      'nfs-hospitable',
      'nfs-properties',
      'nfs-property-view',
      'nfs-checkout',
      'nfs-stripe-checkout',
      'nfs-stripe-webhook',
      'nfs-reservation',
      'nfs-payment-success',
      'nfs-email-send',
      'nfs-operator-dashboard',
    ],
  },
  {
    id: 'crypto',
    label: 'Crypto & Invest',
    icon: '⛓',
    defaultStartId: 'invest-marketplace',
    description: 'Investment marketplace, BNB smart contracts, Particle wallets, blockchain payouts',
    nodeIds: [
      'invest-marketplace',
      'invest-buy-decision',
      'invest-buy-crypto',
      'invest-buy-card',
      'inv-crypto-confirm',
      'samcart-webhook',
      'aff-commission-create',
      'invest-portfolio',
      'invest-proposals',
      'invest-payouts',
      'particle-wallet',
      'particle-generate-jwt',
      'contract-marketplace',
      'contract-rwa',
      'contract-rent',
      'contract-voting',
      'contract-booster',
      'the-graph',
      'admin-invest-orders',
    ],
  },
];

export const VIEW_MAP = new Map(FLOW_VIEWS.map(v => [v.id, v]));
